
name: Chessboard Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        commit_message: Prettier Action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fe_eslint:
    needs: prettier

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    
    - name: Use cached node_modules
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: client

    - name: Install yarn dependencies and Run ESLint for client
      run: |
        cd client
        yarn install
        yarn run lint

    - name: Use cached node_modules
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: frontend
    
    - name: Install yarn dependencies and Run ESLint for main app
      run: |
        cd frontend
        yarn install
        yarn run lint

    - name: Commit changes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Frontend EsLint Fixes
        push_options: '--force'

  be_eslint:
    needs: fe_eslint

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    
    - name: Use cached node_modules
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: backend

    - name: Install yarn dependencies and Run ESLint
      run: |
        cd backend
        yarn install
        yarn run lint --fix

    - name: Commit changes
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Backend EsLint Fixes
        push_options: '--force'

  deploy:
    needs: be_eslint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies and build project
        run: |
          cd backend
          yarn install
          yarn build

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/zc_plugin_chessboard/
            git stash
            git fetch --all
            git reset --hard origin/dev
            cd backend
            yarn install

      - name: Copy Main Chess App dist folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          privateKey: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          localPath: './frontend/dist/'
          remotePath: '/var/www/zc_plugin_chessboard/frontend/dist'

      - name: Copy Client dist folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          privateKey: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          localPath: './client/dist/'
          remotePath: '/var/www/zc_plugin_chessboard/client/dist'

      - name: Restart PM2 Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/zc_plugin_chessboard/backend
            PM2_HOME=/opt/pm2/.pm2 pm2 restart index

